export const IMAGES: Record<
  string,
  Record<string, Record<string, string[]>>
> = {
  binnen: {
    badkamers: {
      'Badkamer (bambou).jpg': ['Badkamer', 'Bambou'],
      'Badkamer (barnwood) 1.jpg': ['Badkamer', 'Barnwood'],
      'Badkamer (barnwood) 2.jpg': ['Badkamer', 'Barnwood'],
      'Badkamer (barnwood) 3.jpg': ['Badkamer', 'Barnwood'],
      'Badkamer (fineer eik) 1.jpg': ['Badkamer', 'Fineer'],
      'Badkamer (fineer eik) 2.jpg': ['Badkamer', 'Fineer'],
      'Badkamer (fineer teak) 1.jpg': ['Badkamer', 'Fineer'],
      'Badkamer (fineer teak) 2.jpg': ['Badkamer', 'Fineer', 'Eik'],
      'Badkamer (Hoogglans melamine) 1.jpg': [
        'Badkamer',
        'Hoogglans',
        'Melamine',
      ],
      'Badkamer (Hoogglans melamine) 2.jpg': [
        'Badkamer',
        'Hoogglans',
        'Melamine',
      ],
      'Badkamer (laminaat).jpg': ['Badkamer', 'Laminaat'],
      'Badkamer (massief eik).jpg': ['Badkamer', 'Massief', 'Eik'],
      'Badkamer (massief notelaar).jpg': ['Badkamer', 'Massief', 'Notelaar'],
      'Badkamer (MDF) 1.jpg': ['Badkamer', 'MDF'],
      'Badkamer (MDF) 2.jpg': ['Badkamer', 'MDF'],
      'Badkamer (MDF) 3.jpg': ['Badkamer', 'MDF'],
      'Badkamer (melamine) 1.jpg': ['Badkamer', 'Melamine'],
      'Badkamer (melamine) 2.jpg': ['Badkamer', 'Melamine'],
      'Douche (teak) 2.jpg': ['Douche', 'Teak'],
    },
    bureaus: {
      'Burelen (donkere eik - wit gelakt - glas).jpg': [
        'Bureau',
        'Donkere Eik',
        'Wit Gelakt',
        'Glas',
      ],
      'Burelen (MDF gegroefde panelen) 1.jpg': [
        'Bureau',
        'MDF',
        'Gegroefde Panelen',
      ],
      'Burelen (MDF gegroefde panelen) 2.jpg': [
        'Bureau',
        'MDF',
        'Gegroefde Panelen',
      ],
      'Burelen (melamine) 1.jpg': ['Bureau', 'Melamine'],
      'Burelen (melamine) 2.jpg': ['Bureau', 'Melamine'],
      'Burelen (wit gelakt) 1.jpg': ['Bureau', 'Wit Gelakt'],
      'Burelen (wit gelakt) 2.jpg': ['Bureau', 'Wit Gelakt'],
    },
    deuren: {
      'Deuren (fineer pallisander).jpg': ['Deur', 'Fineer', 'Pallisander'],
      'Deuren (laminaat).jpg': ['Deur', 'Laminaat'],
      'Deuren (massief eik).jpg': ['Deur', 'Massief', 'Eik'],
      'Deuren (massief grenen).jpg': ['Deur', 'Massief', 'Grenen'],
      'Schuifdeur (massief eik).jpg': ['Schuifdeur', 'Massief', 'Eik'],
    },
    dressings: {
      'Dressings (barnwood LED verlichting).jpg': [
        'Dressing',
        'Barnwood',
        'LED Verlichting',
      ],
      'Dressings (fineer eik).jpg': ['Dressing', 'Fineer', 'Eik'],
      'Dressings (laminaat).jpg': ['Dressing', 'Laminaat'],
      'Dressings (LED verlichting) 1.jpg': ['Dressing', 'LED Verlichting'],
      'Dressings (LED verlichting) 2.jpg': ['Dressing', 'LED Verlichting'],
      'Dressings (MDF gelakt) 1.jpg': ['Dressing', 'MDF', 'Gelakt'],
      'Dressings (MDF gelakt) 2.jpg': ['Dressing', 'MDF', 'Gelakt'],
      'Dressings (melamine) 1.jpg': ['Dressing', 'Melamine'],
      'Dressings (melamine) 2.jpg': ['Dressing', 'Melamine'],
      'Dressings (melamine) 3.jpg': ['Dressing', 'Melamine'],
      'Dressings (melamine) 4.jpg': ['Dressing', 'Melamine'],
    },
    ingemaakte_kasten: {
      'Berging 1.jpg': ['Berging'],
      'Berging 2.jpg': ['Berging'],
      'Bureau in eetkamer.jpg': ['Bureau', 'Eetkamer'],
      'Bureau slaapkamer.jpg': ['Bureau', 'Slaapkamer'],
      'Dressing 1.jpg': ['Dressing'],
      'Dressing 2.jpg': ['Dressing'],
      'DVD en CD kasten 1.jpg': ['DVD', 'CD'],
      'DVD en CD kasten 2.jpg': ['DVD', 'CD'],
      'Game room.jpg': ['Game Room'],
      'Ingemaakte kast - LED.jpg': ['LED'],
      'Ingemaakte kast.jpg': ['Ingemaakte Kast'],
      'Ingemaakte kasten 2.jpg': ['Ingemaakte Kast'],
      'Ingemaakte kasten 3.jpg': ['Ingemaakte Kast'],
      'Kast onder trap (barnwood).jpg': ['Kast', 'Trap', 'Barnwood'],
      'Kast onder trap 1.jpg': ['Kast', 'Trap'],
      'Kast onder trap 2.jpg': ['Kast', 'Trap'],
      'kast voor stationsromans.jpg': [],
      'Kast.jpg': [],
      'Kasten onder schuin dak 1.jpg': [],
      'Kasten onder schuin dak 2.jpg': [],
      'Keukenkast.jpg': [],
      'Ontspanningsruimte.jpg': [],
      'Slaapkamerkast.jpg': [],
      'Spiegeldeuren vestiaire.jpg': [],
      'Technische ruimte 1.jpg': [],
      'Technische ruimte 2.jpg': [],
      'Toilet.jpg': [],
      'Vestiaire.jpg': [],
    },
    interieur_inrichting: {
      'Afwerking radiator.jpg': [],
      'Eetkamer.jpg': [],
      'Massieve tafel met ophangkasten.jpg': [],
      'Ophankasten (MDF gelakt).jpg': [],
      'Schouwwand met bio haard.jpg': [],
      'Schouwwand met gashaard (1).jpg': [],
      'Schouwwand met gashaard (2).jpg': [],
      'Schouwwand met TV-meubel (1).jpg': [],
      'Schouwwand met TV-meubel (2).jpg': [],
      'TV-meubel (massief eik) 10.jpg': [],
      'TV-meubel (massief eik) 2.jpg': [],
      'TV-meubel 1.jpg': [],
      'TV-meubel 2.jpg': [],
      'TV-meubel met bio haard (1).jpg': [],
      'TV-meubel met bio haard (2).jpg': [],
      'TV-wand met schuifdeur.jpg': [],
    },
    keukens: {
      'Keuken (Barnwood).jpg': [],
      'Keuken (laminaat - fineer).jpg': [],
      'Keuken (Zebrano fineer) 1.jpg': [],
      'Keuken (Zebrano fineer) 2.jpg': [],
      'Keuken met draai-inschuifbeslag 1.jpg': [],
      'Keuken met draai-inschuifbeslag 2.jpg': [],
      'Miele koel-en vriescombinatie MasterCool.jpg': [],
      'Uitbreiding keuken.jpg': [],
    },
    meubels: {
      'Ellipsvormige tafel (fineer notelaar - vogeloog esdoorn).jpg': [],
      'Kast met tafel oude eik.jpg': [],
      'Kast oude eik 1.jpg': [],
      'Krukje (massief eik).jpg': [],
    },
    parket: {
      'Boord nieuw.jpg': [],
      'Hongaars Punt 2.jpg': [],
      'Hongaars punt.jpg': [],
      'Lotusbloem (1).jpg': [],
      'Lotusbloem (2).jpg': [],
      'Originele parket.jpg': [],
      'Paneel Spiraal.jpg': [],
      'Parket met bloemetje 1.jpg': [],
      'Parket met bloemetje 2.jpg': [],
      'Ronde parket met tand en groef.jpg': [],
      'Ster.jpg': [],
    },
    slaapkamers: {
      'Colman - Slaapkamers (2).JPG': [],
      'Gsteig JUNI 2012 (82).jpg': [],
      'Gsteig JUNI 2012 (83).jpg': [],
      'Gsteig JUNI 2012 (84).jpg': [],
      'Londen (De Winter Helmert) (21).jpg': [],
      'Van Kerckhoven Patrick (1).JPG': [],
      'Dressing.jpg': [],
    },
    trappen: {
      'Draaitrap (eik - geolied) (1).jpg': [],
      'Draaitrap (eik - geolied) (2).jpg': [],
      'Draaitrap (eik - geolied) (3).jpg': [],
      'Draaitrap (eik - geolied) (4).jpg': [],
      'Draaitrap eik.jpg': [],
      'Pallisander met trap in zwarte MDF.jpg': [],
      'Pallisander.jpg': [],
      'Trap (eik - onbehandeld) (1).jpg': [],
      'Trap (eik - onbehandeld) (2).jpg': [],
      'Trap in Old Boarding 2.jpg': [],
      'Trap in Old Boarding 3.jpg': [],
      'Trap in Old Boarding.jpg': [],
      'Trap in rubberwood 2.jpg': [],
      'Trap in rubberwood.jpg': [],
      'Trap Larix.jpg': [],
    },
    winkels: {
      'DEX.jpg': [],
      'Info & Verkoop - WEBA.jpg': [],
      'Plafond en wand - H-eat.jpg': [],
      'Tafelbladen - Panos 1.jpg': [],
      'Tafelbladen - Panos 2.jpg': [],
    },
  },
  buiten: {
    boten: {
      'Motorjacht vloerdelen in Teak 1.jpg': [],
      'Motorjacht vloerdelen in Teak 2.jpg': [],
      'Vervangen kiel 1.jpg': [],
      'Vervangen kiel 2.jpg': [],
      'Vervangen kiel 3.jpg': [],
    },
    gevelbekleding: {
      'Bekleden sectionaal poort.jpg': [],
      'Garage.jpg': [],
      'Gevelbekleding (Padouk).jpg': [],
      'Gevelbekleding ceder planchetten.jpg': [],
    },
    overkoepeling: {
      'Terrasoverkapping (Padouk).jpg': [],
      'Terrasoverkapping (Teak) 1.jpg': [],
      'Terrasoverkapping (Teak) 2.jpg': [],
    },
    poorten: {
      'Bekleden ijzeren poort 1.jpg': [],
      'Bekleden ijzeren poort 2.jpg': [],
      'Bekleden sectionaal poort.jpg': [],
      'Herstelling poort (teak).jpg': [],
      'Poort (Padouk).jpg': [],
      'Poort (Teak).jpg': [],
      'Tuinpoort (1).jpg': [],
      'Tuinpoort (2).jpg': [],
    },
    terrassen: {
      'Terras.jpg': [],
    },
    tuinmeubelen: {
      'Bank LED-verlichting.jpg': [],
      'Bank.jpg': [],
      'Maatwerk bank.jpg': [],
      'Maatwerk ronde bank.jpg': [],
      'Maatwerk spinnenbank.jpg': [],
      'Maatwerk tafel.jpg': [],
      'Maatwerk zetel.jpg': [],
      'Tuinmeubelen (Inox Padouk).jpg': [],
      'Tuinmeubelen 1.jpg': [],
      'Tuinmeubelen 2.jpg': [],
      'Tuinmeubelen 3.jpg': [],
    },
  },
  overige: {
    allerlei: {
      'Bank LED-verlichting.jpg': [],
      'Coca Cola MP3.jpg': [],
      'Devomat - DevoNaturel Puzzel.jpg': [],
      'Jacqmotte - Passe Café.jpg': [],
      'Koffiepot en deksel.jpg': [],
      'Massieve letters.jpg': [],
      'Puddle.jpg': [],
      'Rookzone.jpg': [],
      'Skateboard.jpg': [],
      'Skateboards.jpg': [],
      'Snijplank.jpg': [],
      'Tafelbladen halve graantjes Panos.jpg': [],
      'Thermowood ballustrade.jpg': [],
      'Zwaluwstaart.jpg': [],
    },
    details: {
      'Barnwood knoest.jpg': [],
      'Barnwood op MX.jpg': [],
      'Barnwood.jpg': [],
      'Bestek Baby.jpg': [],
      'Detail handgreep.jpg': [],
      'Detail schuifgreep.jpg': [],
      'Detail trofee.jpg': [],
      'Gepersonaliseerde locker.jpg': [],
      'Laser.jpg': [],
      'Panos Tafelbladen.jpg': [],
      'Parket met bloemetje.jpg': [],
      'Puddle.jpg': [],
      'QR Codes.jpg': [],
      'Skateboard detail.jpg': [],
    },
    laser: {
      'Bestek Baby.jpg': [],
      'De Autospecialist - Gift.jpg': [],
      'Decospan - Fineer.jpg': [],
      'Histoire A Toi - Juweeltjes.jpg': [],
      'Jacqmotte - iPad casing & inlay.jpg': [],
      'Kampaandenken Chiro.jpg': [],
      'Prijslijst.jpg': [],
      'QR Codes.jpg': [],
      'Skateboards.jpg': [],
      'Trofeën.jpg': [],
    },
  },
};
